jobs:

  build-and-test:

    machine:
      image: ubuntu-2004:202104-01
    steps: 
      - checkout
      - run: make limt
      - run: make test
workflows: 
  basic:  
    jobs: 
      - build-and-test 